<?php

namespace Database\Seeders;

use App\Models\EmployerProfile;
use App\Models\User;
use App\Models\Vacancy;
use Illuminate\Database\Seeder;

class TestVacancySeeder extends Seeder
{
    public function run(): void
    {
        $employers = $this->createEmployers();
        $this->createVacancies($employers);

        $count = count($this->getVacancyData());
        $this->command->info("{$count} ta test vakansiya muvaffaqiyatli yaratildi!");
    }

    private function createEmployers(): array
    {
        $data = [
            [
                'company_name' => 'TechUz Solutions',
                'industry' => 'it',
                'description' => 'O\'zbekistondagi yetakchi IT kompaniya. Web va mobil ilovalar ishlab chiqish.',
                'phone' => '+998901234567',
                'website' => 'https://techuz.uz',
                'employees_count' => '51-200',
                'verification_level' => 'verified',
                'rating' => 4.7,
                'rating_count' => 23,
                'city' => 'Toshkent',
                'latitude' => 41.3111,
                'longitude' => 69.2797,
            ],
            [
                'company_name' => 'Samarqand Grand Hotel',
                'industry' => 'food',
                'description' => 'Samarqand shahridagi 5 yulduzli mehmonxona va restoran tarmog\'i.',
                'phone' => '+998662331122',
                'website' => 'https://samarkand-grand.uz',
                'employees_count' => '201-500',
                'verification_level' => 'verified',
                'rating' => 4.5,
                'rating_count' => 15,
                'city' => 'Samarqand',
                'latitude' => 39.6542,
                'longitude' => 66.9597,
            ],
            [
                'company_name' => 'Farg\'ona Tekstil',
                'industry' => 'production',
                'description' => 'Farg\'ona vodiysidagi yirik to\'qimachilik korxonasi. Eksport yo\'nalishi.',
                'phone' => '+998731234567',
                'website' => null,
                'employees_count' => '500+',
                'verification_level' => 'confirmed',
                'rating' => 4.1,
                'rating_count' => 8,
                'city' => 'Farg\'ona',
                'latitude' => 40.3842,
                'longitude' => 71.7889,
            ],
            [
                'company_name' => 'Buxoro Savdo Markazi',
                'industry' => 'retail',
                'description' => 'Buxoro shahridagi eng yirik savdo markazi. 200+ do\'kon.',
                'phone' => '+998651112233',
                'website' => null,
                'employees_count' => '51-200',
                'verification_level' => 'confirmed',
                'rating' => 3.9,
                'rating_count' => 12,
                'city' => 'Buxoro',
                'latitude' => 39.7747,
                'longitude' => 64.4286,
            ],
            [
                'company_name' => 'Nukus Logistika',
                'industry' => 'logistics',
                'description' => 'Qoraqalpog\'iston bo\'ylab yuk tashish va ombor xizmatlari.',
                'phone' => '+998612345678',
                'website' => null,
                'employees_count' => '11-50',
                'verification_level' => 'new',
                'rating' => 0,
                'rating_count' => 0,
                'city' => 'Nukus',
                'latitude' => 42.4628,
                'longitude' => 59.6003,
            ],
            [
                'company_name' => 'Namangan Building',
                'industry' => 'construction',
                'description' => 'Namangan viloyatidagi qurilish va loyihalash kompaniyasi.',
                'phone' => '+998692223344',
                'website' => null,
                'employees_count' => '51-200',
                'verification_level' => 'confirmed',
                'rating' => 4.3,
                'rating_count' => 6,
                'city' => 'Namangan',
                'latitude' => 40.9983,
                'longitude' => 71.6726,
            ],
            [
                'company_name' => 'Digital Marketing Pro',
                'industry' => 'marketing',
                'description' => 'Raqamli marketing agentligi. SMM, SEO, targetlangan reklama.',
                'phone' => '+998909876543',
                'website' => 'https://dmpro.uz',
                'employees_count' => '11-50',
                'verification_level' => 'verified',
                'rating' => 4.8,
                'rating_count' => 31,
                'city' => 'Toshkent',
                'latitude' => 41.2995,
                'longitude' => 69.2401,
            ],
            [
                'company_name' => 'Qarshi Medical Center',
                'industry' => 'medicine',
                'description' => 'Qashqadaryo viloyatidagi zamonaviy tibbiyot markazi.',
                'phone' => '+998752221133',
                'website' => null,
                'employees_count' => '51-200',
                'verification_level' => 'verified',
                'rating' => 4.6,
                'rating_count' => 19,
                'city' => 'Qarshi',
                'latitude' => 38.8600,
                'longitude' => 65.7983,
            ],
            [
                'company_name' => 'Toshkent Express Delivery',
                'industry' => 'logistics',
                'description' => 'Toshkent shahri bo\'ylab tez yetkazib berish xizmati.',
                'phone' => '+998901001010',
                'website' => 'https://texpress.uz',
                'employees_count' => '11-50',
                'verification_level' => 'verified',
                'rating' => 4.2,
                'rating_count' => 17,
                'city' => 'Toshkent',
                'latitude' => 41.3000,
                'longitude' => 69.2700,
            ],
            [
                'company_name' => 'Andijon Clean Service',
                'industry' => 'cleaning',
                'description' => 'Andijon viloyatida professional tozalash xizmatlari.',
                'phone' => '+998742001020',
                'website' => null,
                'employees_count' => '11-50',
                'verification_level' => 'confirmed',
                'rating' => 4.0,
                'rating_count' => 5,
                'city' => 'Andijon',
                'latitude' => 40.7821,
                'longitude' => 72.3442,
            ],
            [
                'company_name' => 'Jizzax Agro Bank',
                'industry' => 'finance',
                'description' => 'Jizzax viloyatidagi xususiy bank filiali.',
                'phone' => '+998722003040',
                'website' => null,
                'employees_count' => '51-200',
                'verification_level' => 'verified',
                'rating' => 4.4,
                'rating_count' => 10,
                'city' => 'Jizzax',
                'latitude' => 40.1158,
                'longitude' => 67.8422,
            ],
            [
                'company_name' => 'Xorazm Beauty Salon',
                'industry' => 'beauty',
                'description' => 'Urganch shahridagi premium go\'zallik saloni.',
                'phone' => '+998622005060',
                'website' => null,
                'employees_count' => '1-10',
                'verification_level' => 'confirmed',
                'rating' => 4.9,
                'rating_count' => 28,
                'city' => 'Urganch',
                'latitude' => 41.5500,
                'longitude' => 60.6333,
            ],
        ];

        $employers = [];

        foreach ($data as $i => $emp) {
            $user = User::create([
                'telegram_id' => 900000 + $i,
                'first_name' => 'Employer' . ($i + 1),
                'last_name' => 'Test',
                'username' => 'test_employer_' . ($i + 1),
                'language' => 'uz',
                'is_verified' => true,
                'is_blocked' => false,
                'balance' => 500000,
                'last_active_at' => now(),
            ]);

            $profile = EmployerProfile::create([
                'user_id' => $user->id,
                'company_name' => $emp['company_name'],
                'industry' => $emp['industry'],
                'description' => $emp['description'],
                'phone' => $emp['phone'],
                'website' => $emp['website'],
                'employees_count' => $emp['employees_count'],
                'verification_level' => $emp['verification_level'],
                'rating' => $emp['rating'],
                'rating_count' => $emp['rating_count'],
                'latitude' => $emp['latitude'],
                'longitude' => $emp['longitude'],
            ]);

            $user->update(['active_employer_id' => $profile->id]);

            $employers[$emp['company_name']] = $profile;
        }

        return $employers;
    }

    private function getVacancyData(): array
    {
        return [
            // ════════════════════════════════════════
            // IT VA DASTURLASH (7 ta — subcategorylar bo'yicha)
            // ════════════════════════════════════════

            // it-frontend
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'Senior Vue.js Frontend dasturchi',
                'title_ru' => 'Senior Vue.js Frontend разработчик',
                'category' => 'it-frontend',
                'description_uz' => "TechUz Solutions jamoasiga tajribali Vue.js dasturchi kerak.\nBiz SaaS platformalar ishlab chiqamiz. Stek: Vue 3, Nuxt, TypeScript, Tailwind CSS.",
                'description_ru' => "В команду TechUz Solutions требуется опытный Vue.js разработчик.",
                'requirements_uz' => "- Vue 3 + Composition API 2+ yil\n- TypeScript bilimi\n- REST API integratsiya tajribasi",
                'salary_min' => 12000000, 'salary_max' => 20000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => true, 'is_urgent' => false,
                'views_count' => 342, 'applications_count' => 18,
            ],
            // it-backend
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'Senior Laravel Backend dasturchi',
                'title_ru' => 'Senior Laravel Backend разработчик',
                'category' => 'it-backend',
                'description_uz' => "Laravel + PostgreSQL da murakkab API tizimlar ishlab chiqish. Microservice arxitektura.",
                'description_ru' => "Разработка сложных API систем на Laravel + PostgreSQL.",
                'requirements_uz' => "- Laravel 3+ yil\n- MySQL/PostgreSQL\n- Redis, Queue, Docker",
                'salary_min' => 15000000, 'salary_max' => 25000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => true, 'is_urgent' => false,
                'views_count' => 289, 'applications_count' => 14,
            ],
            // it-mobile
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'Middle Flutter dasturchi',
                'title_ru' => 'Middle Flutter разработчик',
                'category' => 'it-mobile',
                'description_uz' => "Fintech va e-commerce ilovalar. 3 ta aktiv mobil loyiha. Flutter, Dart, Firebase, BLoC.",
                'description_ru' => "Fintech и e-commerce приложения. 3 активных мобильных проекта.",
                'requirements_uz' => "- Flutter 2+ yil\n- BLoC/Riverpod\n- REST API integratsiya",
                'salary_min' => 8000000, 'salary_max' => 15000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Mirzo Ulug\'bek',
                'latitude' => 41.3389, 'longitude' => 69.3350,
                'contact_phone' => '+998901234567',
                'is_top' => true, 'is_urgent' => true,
                'views_count' => 523, 'applications_count' => 27,
            ],
            // it-designer
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'UI/UX dizayner (Figma)',
                'title_ru' => 'UI/UX дизайнер (Figma)',
                'category' => 'it-designer',
                'description_uz' => "Mobil ilovalar va web saytlar uchun interfeys dizayni. Figma, prototyping, design system.",
                'description_ru' => "Дизайн интерфейсов для мобильных приложений и веб-сайтов.",
                'requirements_uz' => "- Figma 2+ yil\n- Mobil dizayn tajribasi\n- Portfolio taqdim etish shart",
                'salary_min' => 6000000, 'salary_max' => 12000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 198, 'applications_count' => 22,
            ],
            // it-devops
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'DevOps muhandis (AWS/Docker)',
                'title_ru' => 'DevOps инженер (AWS/Docker)',
                'category' => 'it-devops',
                'description_uz' => "Server infratuzilmasini boshqarish. AWS, Docker, CI/CD pipeline, monitoring.",
                'description_ru' => "Управление серверной инфраструктурой. AWS, Docker, CI/CD.",
                'requirements_uz' => "- Linux admin 3+ yil\n- Docker, Kubernetes\n- AWS yoki GCP tajribasi",
                'salary_min' => 15000000, 'salary_max' => 25000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => false, 'is_urgent' => true,
                'views_count' => 134, 'applications_count' => 6,
            ],
            // it-qa
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'QA muhandis (Manual + Automation)',
                'title_ru' => 'QA инженер (Manual + Automation)',
                'category' => 'it-qa',
                'description_uz' => "Web va mobil ilovalarni testlash. Manual va avtomatlashtirilgan testlar.",
                'description_ru' => "Тестирование веб и мобильных приложений.",
                'requirements_uz' => "- QA tajribasi 1+ yil\n- Selenium/Cypress bilimi\n- API testing (Postman)",
                'salary_min' => 5000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Sergeli',
                'latitude' => 41.2300, 'longitude' => 69.2200,
                'contact_phone' => '+998901234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 87, 'applications_count' => 9,
            ],
            // it-other
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'IT loyiha menejeri',
                'title_ru' => 'IT менеджер проектов',
                'category' => 'it-other',
                'description_uz' => "IT loyihalarni boshqarish. Agile/Scrum metodologiyasi. 3-5 ta parallel loyiha.",
                'description_ru' => "Управление IT проектами. Agile/Scrum.",
                'requirements_uz' => "- IT sohasida 3+ yil\n- Agile/Scrum bilimi\n- Jira/Trello tajribasi",
                'salary_min' => 8000000, 'salary_max' => 14000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Toshkent', 'district' => 'Chilonzor',
                'latitude' => 41.2630, 'longitude' => 69.2086,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 112, 'applications_count' => 8,
            ],

            // ════════════════════════════════════════
            // SOTUVCHI (5 ta)
            // ════════════════════════════════════════

            // sales-shop
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Elektronika do\'kon sotuvchisi',
                'title_ru' => 'Продавец магазина электроники',
                'category' => 'sales-shop',
                'description_uz' => "Buxoro Savdo Markazidagi elektronika do'koniga sotuvchi kerak. Ish grafigi: 09:00-18:00.",
                'description_ru' => "В магазин электроники Бухарского ТЦ требуется продавец.",
                'requirements_uz' => "- Sotuvchilik tajribasi\n- Texnika bilimi\n- Muloqotchanlik",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Buxoro', 'district' => 'Markaz',
                'latitude' => 39.7747, 'longitude' => 64.4286,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 128, 'applications_count' => 9,
            ],
            // sales-consultant
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Kiyim-kechak bo\'limi maslahatchisi',
                'title_ru' => 'Консультант отдела одежды',
                'category' => 'sales-consultant',
                'description_uz' => "Premium kiyim brendlari bo'limida maslahatchi. Mijozlarga yordam va stilistika.",
                'description_ru' => "Консультант в отделе премиум одежды.",
                'requirements_uz' => "- Moda va stilistika qiziqishi\n- Muloqotchanlik\n- Rus tili bilishi afzal",
                'salary_min' => 2500000, 'salary_max' => 4500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Buxoro', 'district' => 'Markaz',
                'latitude' => 39.7747, 'longitude' => 64.4286,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 76, 'applications_count' => 5,
            ],
            // sales-cashier
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Kassir (supermarket)',
                'title_ru' => 'Кассир (супермаркет)',
                'category' => 'sales-cashier',
                'description_uz' => "Supermarketga kassir kerak. Navbatli ish grafigi. Tushlik bepul.",
                'description_ru' => "В супермаркет требуется кассир. Сменный график.",
                'requirements_uz' => "- Kassa apparati bilan ishlash\n- Diqqatlilik\n- 18+ yosh",
                'salary_min' => 2000000, 'salary_max' => 3000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Buxoro', 'district' => 'Markaz',
                'latitude' => 39.7747, 'longitude' => 64.4286,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => true,
                'views_count' => 54, 'applications_count' => 3,
            ],
            // sales-wholesale
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Ulgurji savdo menejeri',
                'title_ru' => 'Менеджер оптовых продаж',
                'category' => 'sales-wholesale',
                'description_uz' => "Tekstil mahsulotlarini ulgurji sotish. Korxona mijozlar bazasini kengaytirish.",
                'description_ru' => "Оптовая продажа текстильной продукции.",
                'requirements_uz' => "- Savdo tajribasi 2+ yil\n- Muzokaralar olib borish\n- Haydovchilik guvohnomasi",
                'salary_min' => 5000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => null,
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 95, 'applications_count' => 7,
            ],
            // sales-market
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Bozor savdogari (meva-sabzavot)',
                'title_ru' => 'Продавец на рынке (овощи-фрукты)',
                'category' => 'sales-market',
                'description_uz' => "Dehqon bozorida meva-sabzavot sotish. Ertalabki smena 06:00-14:00.",
                'description_ru' => "Продажа овощей и фруктов на рынке.",
                'requirements_uz' => "- Jismoniy sog'lom\n- Erta turish imkoniyati\n- Tajriba shart emas",
                'salary_min' => 2000000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Buxoro', 'district' => 'Bozor',
                'latitude' => 39.7700, 'longitude' => 64.4200,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 42, 'applications_count' => 2,
            ],

            // ════════════════════════════════════════
            // OSHXONA VA RESTORAN (5 ta)
            // ════════════════════════════════════════

            // food-cook
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Bosh oshpaz (European & O\'zbek)',
                'title_ru' => 'Шеф-повар (европейская и узбекская кухня)',
                'category' => 'food-cook',
                'description_uz' => "5 yulduzli mehmonxona restoraniga bosh oshpaz. Kuniga 200+ mehmon.",
                'description_ru' => "В ресторан 5-звездочного отеля требуется шеф-повар.",
                'requirements_uz' => "- Oshpazlik 5+ yil\n- Yevropa va O'zbek taomlari\n- Jamoa boshqarish",
                'salary_min' => 8000000, 'salary_max' => 15000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '5+',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => true,
                'views_count' => 187, 'applications_count' => 7,
            ],
            // food-waiter
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Ofitsiant (premium restoran)',
                'title_ru' => 'Официант (премиум ресторан)',
                'category' => 'food-waiter',
                'description_uz' => "Premium restoraniga ofitsiant kerak. Ingliz tili bilishi afzal.",
                'description_ru' => "Требуется официант в премиум ресторан.",
                'requirements_uz' => "- Xizmat ko'rsatish tajribasi\n- Yoqimli tashqi ko'rinish\n- Ingliz tili afzal",
                'salary_min' => 2500000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 143, 'applications_count' => 11,
            ],
            // food-barista
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Barista (lobby coffee bar)',
                'title_ru' => 'Бариста (кофе-бар в лобби)',
                'category' => 'food-barista',
                'description_uz' => "Mehmonxona lobbi kafe-barga barista kerak. Professional qahva tayyorlash.",
                'description_ru' => "Бариста в кофе-бар лобби отеля.",
                'requirements_uz' => "- Barista tajribasi 6+ oy\n- Latte art bilimi\n- Muloqotchanlik",
                'salary_min' => 2000000, 'salary_max' => 3500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 98, 'applications_count' => 6,
            ],
            // food-baker
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Novvoy (non va pishiriqlar)',
                'title_ru' => 'Пекарь (хлеб и выпечка)',
                'category' => 'food-baker',
                'description_uz' => "Mehmonxona novvoyxonasiga novvoy. Milliy non va yevropa pishiriqlari.",
                'description_ru' => "Пекарь в пекарню отеля.",
                'requirements_uz' => "- Novvoylik tajribasi 2+ yil\n- Non va pishiriq retseptlari",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 67, 'applications_count' => 4,
            ],
            // food-dishwasher
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Idish yuvuvchi (restoran)',
                'title_ru' => 'Посудомойщик (ресторан)',
                'category' => 'food-dishwasher',
                'description_uz' => "Restoraniga idish yuvuvchi kerak. Tushlik bepul, transport xizmati.",
                'description_ru' => "Посудомойщик в ресторан отеля.",
                'requirements_uz' => "- Tajriba shart emas\n- Mas'uliyatlilik\n- 18+ yosh",
                'salary_min' => 1800000, 'salary_max' => 2500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 31, 'applications_count' => 2,
            ],

            // ════════════════════════════════════════
            // HAYDOVCHI (4 ta)
            // ════════════════════════════════════════

            // driver-taxi
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Taksi haydovchisi (Yandex/MyTaxi)',
                'title_ru' => 'Водитель такси (Yandex/MyTaxi)',
                'category' => 'driver-taxi',
                'description_uz' => "O'z mashinangiz bilan taksi haydovchisi. Moslashuvchan grafik.",
                'description_ru' => "Водитель такси на своём автомобиле.",
                'requirements_uz' => "- B toifali guvohnoma\n- O'z mashinasi\n- Toshkentni yaxshi bilish",
                'salary_min' => 4000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 234, 'applications_count' => 15,
            ],
            // driver-truck
            [
                'employer' => 'Nukus Logistika',
                'title_uz' => 'Yuk mashina haydovchisi (shaharlararo)',
                'title_ru' => 'Водитель грузовика (междугородний)',
                'category' => 'driver-truck',
                'description_uz' => "Shaharlararo yuk tashish. Nukus-Toshkent, Nukus-Buxoro yo'nalishlari. Mashina kompaniyadan.",
                'description_ru' => "Междугородние грузоперевозки.",
                'requirements_uz' => "- BC toifali guvohnoma\n- Yuk tashish 3+ yil\n- Jinoyat yozuvi yo'q",
                'salary_min' => 6000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Nukus', 'district' => null,
                'latitude' => 42.4628, 'longitude' => 59.6003,
                'contact_phone' => '+998612345678',
                'is_top' => false, 'is_urgent' => true,
                'views_count' => 64, 'applications_count' => 3,
            ],
            // driver-delivery
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Kuryer-haydovchi (shahar ichida)',
                'title_ru' => 'Курьер-водитель (по городу)',
                'category' => 'driver-delivery',
                'description_uz' => "Toshkent shahar ichida buyurtmalar yetkazish. Kuniga 15-20 ta buyurtma.",
                'description_ru' => "Доставка заказов по городу Ташкент.",
                'requirements_uz' => "- B toifali guvohnoma\n- Smartfon\n- Navigatsiya bilimi",
                'salary_min' => 3500000, 'salary_max' => 7000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 178, 'applications_count' => 12,
            ],
            // driver-personal
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Shaxsiy haydovchi (direktor uchun)',
                'title_ru' => 'Личный водитель (для директора)',
                'category' => 'driver-personal',
                'description_uz' => "Kompaniya direktori uchun shaxsiy haydovchi. Toyota Camry.",
                'description_ru' => "Личный водитель для директора компании.",
                'requirements_uz' => "- B toifali 5+ yil tajriba\n- Ehtiyotkor haydash\n- Toza ko'rinish",
                'salary_min' => 4000000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Toshkent', 'district' => 'Chilonzor',
                'latitude' => 41.2630, 'longitude' => 69.2086,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 89, 'applications_count' => 6,
            ],

            // ════════════════════════════════════════
            // QURILISH (6 ta)
            // ════════════════════════════════════════

            // construction-builder
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Qurilish boshqaruvchisi (Prorab)',
                'title_ru' => 'Прораб (руководитель строительства)',
                'category' => 'construction-builder',
                'description_uz' => "16 qavatli 3 ta bino qurilishi. Loyiha muddati 18 oy. 50+ ishchi jamoasi.",
                'description_ru' => "Строительство 3 зданий по 16 этажей. Срок 18 месяцев.",
                'requirements_uz' => "- Qurilish 5+ yil\n- Ko'p qavatli bino tajribasi\n- SNiP bilimi",
                'salary_min' => 10000000, 'salary_max' => 18000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '5+',
                'city' => 'Namangan', 'district' => 'Yangi Namangan',
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => true, 'is_urgent' => false,
                'views_count' => 215, 'applications_count' => 11,
            ],
            // construction-electrician
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Elektrchi (ko\'p qavatli bino)',
                'title_ru' => 'Электрик (многоэтажка)',
                'category' => 'construction-electrician',
                'description_uz' => "Yangi qurilish loyihasida elektr tizimlarni o'rnatish.",
                'description_ru' => "Монтаж электросистем в новостройке.",
                'requirements_uz' => "- Elektr montaj 3+ yil\n- Xavfsizlik qoidalari\n- Sertifikat",
                'salary_min' => 5000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Namangan', 'district' => 'Yangi Namangan',
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 78, 'applications_count' => 5,
            ],
            // construction-plumber
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Santexnik (yangi qurilish)',
                'title_ru' => 'Сантехник (новостройка)',
                'category' => 'construction-plumber',
                'description_uz' => "Suv va kanalizatsiya tizimlarini o'rnatish.",
                'description_ru' => "Монтаж водоснабжения и канализации.",
                'requirements_uz' => "- Santexnika 2+ yil\n- Polipropilen quvurlar bilan ishlash",
                'salary_min' => 4000000, 'salary_max' => 7000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Namangan', 'district' => 'Yangi Namangan',
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 56, 'applications_count' => 3,
            ],
            // construction-painter
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Bo\'yoqchi (ichki dekor)',
                'title_ru' => 'Маляр (внутренняя отделка)',
                'category' => 'construction-painter',
                'description_uz' => "Kvartiralar ichki bo'yash ishlari. Dekorativ shtukaturka.",
                'description_ru' => "Покраска квартир. Декоративная штукатурка.",
                'requirements_uz' => "- Bo'yash tajribasi 1+ yil\n- Dekorativ texnikalar bilimi",
                'salary_min' => 3000000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Namangan', 'district' => null,
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 43, 'applications_count' => 2,
            ],
            // construction-welder
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Payvandchi (metall konstruksiyalar)',
                'title_ru' => 'Сварщик (металлоконструкции)',
                'category' => 'construction-welder',
                'description_uz' => "Metall konstruksiyalarni payvandlash. Argon va elektr payvand.",
                'description_ru' => "Сварка металлоконструкций. Аргон и электросварка.",
                'requirements_uz' => "- Payvandchi sertifikati\n- 3+ yil tajriba\n- Balandlikda ishlash",
                'salary_min' => 5000000, 'salary_max' => 9000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Namangan', 'district' => null,
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => true,
                'views_count' => 67, 'applications_count' => 4,
            ],
            // construction-carpenter
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Duradgor (yog\'och ishlar)',
                'title_ru' => 'Плотник (столярные работы)',
                'category' => 'construction-carpenter',
                'description_uz' => "Eshik, deraza va mebel o'rnatish ishlari.",
                'description_ru' => "Установка дверей, окон и мебели.",
                'requirements_uz' => "- Duradgorlik 2+ yil\n- O'lchash asboblari bilan ishlash",
                'salary_min' => 3500000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Namangan', 'district' => null,
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 38, 'applications_count' => 2,
            ],

            // ════════════════════════════════════════
            // GO'ZALLIK VA SOG'LIQ (6 ta)
            // ════════════════════════════════════════

            // beauty-hairdresser
            [
                'employer' => 'Xorazm Beauty Salon',
                'title_uz' => 'Sartarosh (erkak va ayol)',
                'title_ru' => 'Парикмахер (мужской и женский)',
                'category' => 'beauty-hairdresser',
                'description_uz' => "Premium go'zallik saloniga sartarosh. Ijara emas, oylik maosh + %.",
                'description_ru' => "Парикмахер в премиум салон красоты.",
                'requirements_uz' => "- Sartaroshlik 2+ yil\n- Zamonaviy uslublar bilimi\n- Portfolio",
                'salary_min' => 3000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Urganch', 'district' => null,
                'latitude' => 41.5500, 'longitude' => 60.6333,
                'contact_phone' => '+998622005060',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 156, 'applications_count' => 9,
            ],
            // beauty-manicure
            [
                'employer' => 'Xorazm Beauty Salon',
                'title_uz' => 'Manikur va pedikur ustasi',
                'title_ru' => 'Мастер маникюра и педикюра',
                'category' => 'beauty-manicure',
                'description_uz' => "Gel lak, dizayn, pedikur. Asboblar salon tomonidan.",
                'description_ru' => "Гель-лак, дизайн, педикюр.",
                'requirements_uz' => "- Manikur tajribasi 1+ yil\n- Gel lak texnikasi\n- Sertifikat afzal",
                'salary_min' => 2500000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Urganch', 'district' => null,
                'latitude' => 41.5500, 'longitude' => 60.6333,
                'contact_phone' => '+998622005060',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 134, 'applications_count' => 8,
            ],
            // beauty-cosmetologist
            [
                'employer' => 'Qarshi Medical Center',
                'title_uz' => 'Kosmetolog (apparatli kosmetologiya)',
                'title_ru' => 'Косметолог (аппаратная косметология)',
                'category' => 'beauty-cosmetologist',
                'description_uz' => "Zamonaviy lazer va apparatli kosmetologiya xizmatlari.",
                'description_ru' => "Лазерная и аппаратная косметология.",
                'requirements_uz' => "- Tibbiy ma'lumot\n- Kosmetologiya sertifikati\n- Apparat tajribasi",
                'salary_min' => 5000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Qarshi', 'district' => 'Markaz',
                'latitude' => 38.8600, 'longitude' => 65.7983,
                'contact_phone' => '+998752221133',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 89, 'applications_count' => 5,
            ],
            // beauty-nurse
            [
                'employer' => 'Qarshi Medical Center',
                'title_uz' => 'Oliy toifali hamshira',
                'title_ru' => 'Медсестра высшей категории',
                'category' => 'beauty-nurse',
                'description_uz' => "Terapiya bo'limi. Zamonaviy asbob-uskunalar, malaka oshirish imkoniyati.",
                'description_ru' => "Терапевтическое отделение.",
                'requirements_uz' => "- Tibbiy ma'lumot\n- Hamshiralik 2+ yil\n- Tibbiy asboblar bilimi",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Qarshi', 'district' => 'Markaz',
                'latitude' => 38.8600, 'longitude' => 65.7983,
                'contact_phone' => '+998752221133',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 73, 'applications_count' => 5,
            ],
            // beauty-pharmacist
            [
                'employer' => 'Qarshi Medical Center',
                'title_uz' => 'Farmatsevt (dorixona)',
                'title_ru' => 'Фармацевт (аптека)',
                'category' => 'beauty-pharmacist',
                'description_uz' => "Tibbiyot markazi qoshidagi dorixonaga farmatsevt.",
                'description_ru' => "Фармацевт в аптеку при медцентре.",
                'requirements_uz' => "- Farmatsevtika ma'lumoti\n- Dori-darmonlar bilimi\n- Litsenziya",
                'salary_min' => 3500000, 'salary_max' => 5500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Qarshi', 'district' => 'Markaz',
                'latitude' => 38.8600, 'longitude' => 65.7983,
                'contact_phone' => '+998752221133',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 45, 'applications_count' => 3,
            ],
            // beauty-masseur
            [
                'employer' => 'Xorazm Beauty Salon',
                'title_uz' => 'Massajchi (klassik va sport)',
                'title_ru' => 'Массажист (классический и спортивный)',
                'category' => 'beauty-masseur',
                'description_uz' => "Klassik, sport va relaks massaj xizmatlari.",
                'description_ru' => "Классический, спортивный и релакс массаж.",
                'requirements_uz' => "- Massaj sertifikati\n- 1+ yil tajriba",
                'salary_min' => 3000000, 'salary_max' => 7000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Urganch', 'district' => null,
                'latitude' => 41.5500, 'longitude' => 60.6333,
                'contact_phone' => '+998622005060',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 67, 'applications_count' => 4,
            ],

            // ════════════════════════════════════════
            // TA'LIM (4 ta)
            // ════════════════════════════════════════

            // education-teacher
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Ingliz tili o\'qituvchisi (korporativ)',
                'title_ru' => 'Преподаватель английского (корпоративный)',
                'category' => 'education-teacher',
                'description_uz' => "Xodimlar uchun ingliz tili. Haftada 3 kun, har kuni 2 soat.",
                'description_ru' => "Английский для сотрудников. 3 дня в неделю по 2 часа.",
                'requirements_uz' => "- CEFR B2+ daraja\n- O'qituvchilik 1+ yil\n- Kattalar bilan ishlash",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'part_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => null,
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 112, 'applications_count' => 8,
            ],
            // education-tutor
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Matematika repetitori (online)',
                'title_ru' => 'Репетитор по математике (онлайн)',
                'category' => 'education-tutor',
                'description_uz' => "Online matematika darslari. 9-11 sinf o'quvchilari. Zoom/Google Meet.",
                'description_ru' => "Онлайн уроки математики для 9-11 классов.",
                'requirements_uz' => "- Matematika bilimi\n- Online dars tajribasi\n- Sabr-toqat",
                'salary_min' => 2000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 87, 'applications_count' => 6,
            ],
            // education-trainer
            [
                'employer' => 'Qarshi Medical Center',
                'title_uz' => 'Fitness trener (sport zal)',
                'title_ru' => 'Фитнес тренер (спортзал)',
                'category' => 'education-trainer',
                'description_uz' => "Sport zalga fitness trener. Individual va guruh mashg'ulotlari.",
                'description_ru' => "Фитнес тренер в спортзал.",
                'requirements_uz' => "- Sport ma'lumoti\n- Trenerlik sertifikati\n- Jismoniy sog'lom",
                'salary_min' => 2500000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Qarshi', 'district' => null,
                'latitude' => 38.8600, 'longitude' => 65.7983,
                'contact_phone' => '+998752221133',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 56, 'applications_count' => 3,
            ],
            // education-nanny
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Bolalar tarbiyachisi (3-6 yosh)',
                'title_ru' => 'Воспитатель (3-6 лет)',
                'category' => 'education-nanny',
                'description_uz' => "Xususiy bolalar bog'chasiga tarbiyachi. 3-6 yoshli bolalar guruhi.",
                'description_ru' => "Воспитатель в частный детский сад.",
                'requirements_uz' => "- Pedagogik ma'lumot\n- Bolalar bilan ishlash tajribasi\n- Sabr va g'amxo'rlik",
                'salary_min' => 2500000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Yakkasaroy',
                'latitude' => 41.2900, 'longitude' => 69.2700,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 98, 'applications_count' => 7,
            ],

            // ════════════════════════════════════════
            // MOLIYA (4 ta)
            // ════════════════════════════════════════

            // finance-accountant
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Buxgalter (1C va soliq hisoboti)',
                'title_ru' => 'Бухгалтер (1С и налоговая отчётность)',
                'category' => 'finance-accountant',
                'description_uz' => "Moliyaviy hisobotlar va soliq deklaratsiyalari. 1C dasturi.",
                'description_ru' => "Финансовая отчётность и налоговые декларации.",
                'requirements_uz' => "- Buxgalterlik 2+ yil\n- 1C bilimi\n- Soliq qonunchiligi",
                'salary_min' => 5000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Chilonzor',
                'latitude' => 41.2630, 'longitude' => 69.2086,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 167, 'applications_count' => 14,
            ],
            // finance-economist
            [
                'employer' => 'Jizzax Agro Bank',
                'title_uz' => 'Iqtisodchi (kredit bo\'limi)',
                'title_ru' => 'Экономист (кредитный отдел)',
                'category' => 'finance-economist',
                'description_uz' => "Kredit arizalarni tahlil qilish va moliyaviy hisob-kitob.",
                'description_ru' => "Анализ кредитных заявок и финансовые расчёты.",
                'requirements_uz' => "- Iqtisodiyot ma'lumoti\n- Moliyaviy tahlil\n- Excel bilimi",
                'salary_min' => 4000000, 'salary_max' => 7000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Jizzax', 'district' => null,
                'latitude' => 40.1158, 'longitude' => 67.8422,
                'contact_phone' => '+998722003040',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 78, 'applications_count' => 5,
            ],
            // finance-banker
            [
                'employer' => 'Jizzax Agro Bank',
                'title_uz' => 'Bank kassiri',
                'title_ru' => 'Банковский кассир',
                'category' => 'finance-banker',
                'description_uz' => "Kassa operatsiyalari. Naqd pul va plastik kartalar bilan ishlash.",
                'description_ru' => "Кассовые операции. Наличные и пластиковые карты.",
                'requirements_uz' => "- Moliya ma'lumoti\n- Diqqatlilik\n- Kassa tajribasi afzal",
                'salary_min' => 3500000, 'salary_max' => 5500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Jizzax', 'district' => null,
                'latitude' => 40.1158, 'longitude' => 67.8422,
                'contact_phone' => '+998722003040',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 56, 'applications_count' => 4,
            ],
            // finance-auditor
            [
                'employer' => 'Jizzax Agro Bank',
                'title_uz' => 'Ichki auditor',
                'title_ru' => 'Внутренний аудитор',
                'category' => 'finance-auditor',
                'description_uz' => "Bank ichki audit jarayonlari. Xavf tahlili va nazorat.",
                'description_ru' => "Внутренний аудит банка. Анализ рисков и контроль.",
                'requirements_uz' => "- Audit tajribasi 3+ yil\n- ACCA/CIA sertifikat afzal\n- Analitik fikrlash",
                'salary_min' => 7000000, 'salary_max' => 12000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '3-5',
                'city' => 'Jizzax', 'district' => null,
                'latitude' => 40.1158, 'longitude' => 67.8422,
                'contact_phone' => '+998722003040',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 34, 'applications_count' => 2,
            ],

            // ════════════════════════════════════════
            // MARKETING (9 ta)
            // ════════════════════════════════════════

            // marketing-smm
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'SMM mutaxassisi (Instagram + Telegram)',
                'title_ru' => 'SMM специалист (Instagram + Telegram)',
                'category' => 'marketing-smm',
                'description_uz' => "5-8 ta brendning ijtimoiy tarmoqlari. Remote ishlash, moslashuvchan grafik.",
                'description_ru' => "Ведение соцсетей 5-8 брендов. Удалённая работа.",
                'requirements_uz' => "- SMM 1+ yil\n- Reels va Telegram\n- Canva/Figma\n- Portfolio",
                'salary_min' => 4000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 456, 'applications_count' => 34,
            ],
            // marketing-content
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Kontent menejeri (O\'zbek tili)',
                'title_ru' => 'Контент менеджер (узбекский язык)',
                'category' => 'marketing-content',
                'description_uz' => "O'zbek tilida kontent yaratish. Blog, ijtimoiy tarmoq postlari, email.",
                'description_ru' => "Создание контента на узбекском языке.",
                'requirements_uz' => "- O'zbek tilida yaxshi yozish\n- Copywriting bilimi\n- SEO asoslari",
                'salary_min' => 3000000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 178, 'applications_count' => 12,
            ],
            // marketing-seo
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'SEO mutaxassisi',
                'title_ru' => 'SEO специалист',
                'category' => 'marketing-seo',
                'description_uz' => "Kompaniya va mijozlar saytlarini SEO optimizatsiya qilish.",
                'description_ru' => "SEO оптимизация сайтов компании и клиентов.",
                'requirements_uz' => "- SEO 2+ yil\n- Google Analytics/Search Console\n- Texnik SEO bilimi",
                'salary_min' => 5000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 123, 'applications_count' => 8,
            ],
            // marketing-designer
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Grafik dizayner (brending)',
                'title_ru' => 'Графический дизайнер (брендинг)',
                'category' => 'marketing-designer',
                'description_uz' => "Brendlar uchun vizual kontent. Logotip, banner, packaging.",
                'description_ru' => "Визуальный контент для брендов. Логотип, баннеры.",
                'requirements_uz' => "- Adobe CC (Photoshop, Illustrator)\n- Brending tajribasi\n- Portfolio",
                'salary_min' => 4000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Chilonzor',
                'latitude' => 41.2630, 'longitude' => 69.2086,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 145, 'applications_count' => 10,
            ],
            // marketing-targetolog
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Targetolog (Facebook/Instagram Ads)',
                'title_ru' => 'Таргетолог (Facebook/Instagram Ads)',
                'category' => 'marketing-targetolog',
                'description_uz' => "Target reklama kampaniyalarni boshqarish. A/B testing, analitika.",
                'description_ru' => "Управление таргетированной рекламой.",
                'requirements_uz' => "- Facebook Ads 1+ yil\n- Analitika va A/B testing\n- Byudjet boshqarish",
                'salary_min' => 5000000, 'salary_max' => 12000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 198, 'applications_count' => 15,
            ],

            // marketing-sales-manager
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Sotuv menejeri (korporativ mijozlar)',
                'title_ru' => 'Менеджер по продажам (корпоративные клиенты)',
                'category' => 'marketing-sales-manager',
                'description_uz' => "Tekstil mahsulotlarini korporativ mijozlarga sotish. B2B savdo, shartnomalar tuzish, CRM yuritish.\n\nMijozlar bazasini kengaytirish va mavjud mijozlarni ushlab turish. Oylik reja + bonus tizimi.",
                'description_ru' => "Продажа текстильной продукции корпоративным клиентам. B2B продажи, заключение контрактов.",
                'requirements_uz' => "- Savdo tajribasi 2+ yil\n- B2B sotuvlar bo'yicha bilim\n- CRM tizimlarida ishlash\n- Muzokaralar olib borish qobiliyati\n- Haydovchilik guvohnomasi afzal",
                'salary_min' => 5000000, 'salary_max' => 15000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => null,
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 167, 'applications_count' => 11,
            ],
            // marketing-marketolog
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'Marketolog (IT kompaniya)',
                'title_ru' => 'Маркетолог (IT компания)',
                'category' => 'marketing-marketolog',
                'description_uz' => "IT kompaniya uchun marketing strategiyasini ishlab chiqish va amalga oshirish.\n\nBrand awareness oshirish, lead generation, marketing kampaniyalar. Analitika va ROI hisob-kitob.",
                'description_ru' => "Разработка и реализация маркетинговой стратегии IT компании.\n\nBrand awareness, lead generation, маркетинговые кампании.",
                'requirements_uz' => "- Marketing tajribasi 2+ yil\n- Digital marketing bilimi\n- Google Analytics, Data Studio\n- Ingliz tili (B1+)\n- IT sohasini tushunish afzal",
                'salary_min' => 7000000, 'salary_max' => 14000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => true, 'is_urgent' => false,
                'views_count' => 245, 'applications_count' => 19,
            ],
            // marketing-sales-operator
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Sotuv operatori (telefon orqali)',
                'title_ru' => 'Оператор продаж (по телефону)',
                'category' => 'marketing-sales-operator',
                'description_uz' => "Telefon orqali xizmatlarni taklif qilish va sotish. Kuniga 50-80 ta qo'ng'iroq.\n\nO'quv dasturi beriladi. Asosiy maosh + har bir sotuvdan bonus.",
                'description_ru' => "Продажа услуг по телефону. 50-80 звонков в день.\n\nОбучение предоставляется. Оклад + бонус за каждую продажу.",
                'requirements_uz' => "- Yoqimli ovoz va nutq\n- Stressga chidamlilik\n- Sotuvga qiziqish\n- Kompyuter bilimi\n- Tajriba shart emas — o'rgatamiz",
                'salary_min' => 3000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => 41.3000, 'longitude' => 69.2700,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 189, 'applications_count' => 14,
            ],
            // marketing-pr
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'PR mutaxassisi (mehmonxona)',
                'title_ru' => 'PR специалист (гостиница)',
                'category' => 'marketing-pr',
                'description_uz' => "5 yulduzli mehmonxona uchun PR strategiyasi. OAV bilan ishlash, press-relizlar, tadbirlar tashkil etish.\n\nMehmonxona brendini rivojlantirish va ommaga tanishtirilgan tadbirlar.",
                'description_ru' => "PR стратегия для 5-звёздочного отеля. Работа со СМИ, пресс-релизы, организация мероприятий.",
                'requirements_uz' => "- PR/Jurnalistika tajribasi 2+ yil\n- OAV bilan aloqalar\n- Ijtimoiy tarmoqlar bilimi\n- O'zbek va rus tilida yozish\n- Ingliz tili afzal",
                'salary_min' => 5000000, 'salary_max' => 10000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 87, 'applications_count' => 5,
            ],

            // ════════════════════════════════════════
            // LOGISTIKA (4 ta)
            // ════════════════════════════════════════

            // logistics-warehouse
            [
                'employer' => 'Nukus Logistika',
                'title_uz' => 'Omborchi (katta ombor)',
                'title_ru' => 'Кладовщик (большой склад)',
                'category' => 'logistics-warehouse',
                'description_uz' => "Katta omborni boshqarish. Kirim-chiqim hisob-kitob.",
                'description_ru' => "Управление большим складом. Учёт прихода-расхода.",
                'requirements_uz' => "- Ombor tajribasi 1+ yil\n- Kompyuter bilimi\n- Jismoniy sog'lom",
                'salary_min' => 2500000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Nukus', 'district' => null,
                'latitude' => 42.4628, 'longitude' => 59.6003,
                'contact_phone' => '+998612345678',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 45, 'applications_count' => 3,
            ],
            // logistics-courier
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Piyoda kuryer (Toshkent markaz)',
                'title_ru' => 'Пеший курьер (центр Ташкента)',
                'category' => 'logistics-courier',
                'description_uz' => "Toshkent markazi bo'ylab piyoda yetkazish. Kuniga 10-15 buyurtma.",
                'description_ru' => "Пешая доставка по центру Ташкента.",
                'requirements_uz' => "- Jismoniy sog'lom\n- Smartfon\n- 18+ yosh",
                'salary_min' => 2000000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'part_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => 'Markaz',
                'latitude' => 41.3100, 'longitude' => 69.2800,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 234, 'applications_count' => 18,
            ],
            // logistics-loader
            [
                'employer' => 'Nukus Logistika',
                'title_uz' => 'Yukchi (ombor)',
                'title_ru' => 'Грузчик (склад)',
                'category' => 'logistics-loader',
                'description_uz' => "Omborga yukchi. Yuklarni qabul qilish va joylashtirish.",
                'description_ru' => "Грузчик на склад. Приём и размещение грузов.",
                'requirements_uz' => "- Jismoniy sog'lom\n- Tajriba shart emas\n- Mas'uliyatlilik",
                'salary_min' => 2000000, 'salary_max' => 3000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Nukus', 'district' => null,
                'latitude' => 42.4628, 'longitude' => 59.6003,
                'contact_phone' => '+998612345678',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 32, 'applications_count' => 2,
            ],
            // logistics-dispatcher
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Dispetcher (buyurtmalar taqsimoti)',
                'title_ru' => 'Диспетчер (распределение заказов)',
                'category' => 'logistics-dispatcher',
                'description_uz' => "Buyurtmalarni kuryer va haydovchilarga taqsimlash. CRM tizimda ishlash.",
                'description_ru' => "Распределение заказов между курьерами.",
                'requirements_uz' => "- Kompyuter bilimi\n- Stressga chidamlilik\n- Logistika tushunchasi",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => 41.3000, 'longitude' => 69.2700,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 67, 'applications_count' => 5,
            ],

            // ════════════════════════════════════════
            // QO'RIQLASH (2 ta)
            // ════════════════════════════════════════

            // security-guard
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Qo\'riqchi (tungi smena)',
                'title_ru' => 'Охранник (ночная смена)',
                'category' => 'security-guard',
                'description_uz' => "Savdo markaziga tungi qo'riqchi. 20:00-08:00, 2/2 navbat.",
                'description_ru' => "Ночная охрана торгового центра. 20:00-08:00.",
                'requirements_uz' => "- 22-50 yosh\n- Jinoyat yozuvi yo'q\n- Harbiy xizmatdan o'tgan",
                'salary_min' => 2500000, 'salary_max' => 3500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Buxoro', 'district' => 'Markaz',
                'latitude' => 39.7747, 'longitude' => 64.4286,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 45, 'applications_count' => 4,
            ],
            // security-cctv
            [
                'employer' => 'Buxoro Savdo Markazi',
                'title_uz' => 'Kuzatuv kameralar operatori',
                'title_ru' => 'Оператор видеонаблюдения',
                'category' => 'security-cctv',
                'description_uz' => "Kuzatuv kameralar tizimini boshqarish. 50+ kamera monitoring.",
                'description_ru' => "Управление системой видеонаблюдения. 50+ камер.",
                'requirements_uz' => "- Kompyuter bilimi\n- Diqqatlilik\n- Kuzatuv tajribasi afzal",
                'salary_min' => 2800000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Buxoro', 'district' => 'Markaz',
                'latitude' => 39.7747, 'longitude' => 64.4286,
                'contact_phone' => '+998651112233',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 34, 'applications_count' => 2,
            ],

            // ════════════════════════════════════════
            // TOZALASH (3 ta)
            // ════════════════════════════════════════

            // cleaning-office
            [
                'employer' => 'Andijon Clean Service',
                'title_uz' => 'Ofis tozalagich',
                'title_ru' => 'Уборщик офиса',
                'category' => 'cleaning-office',
                'description_uz' => "Ofis binolarini tozalash. Ertalabki smena 06:00-14:00.",
                'description_ru' => "Уборка офисных зданий. Утренняя смена.",
                'requirements_uz' => "- Tajriba shart emas\n- Mas'uliyatlilik\n- 18+ yosh",
                'salary_min' => 1800000, 'salary_max' => 2500000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Andijon', 'district' => null,
                'latitude' => 40.7821, 'longitude' => 72.3442,
                'contact_phone' => '+998742001020',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 28, 'applications_count' => 2,
            ],
            // cleaning-home
            [
                'employer' => 'Andijon Clean Service',
                'title_uz' => 'Uy tozalagich (xususiy uylar)',
                'title_ru' => 'Домработница (частные дома)',
                'category' => 'cleaning-home',
                'description_uz' => "Xususiy uylarni tozalash xizmati. Buyurtma asosida.",
                'description_ru' => "Уборка частных домов. По заказу.",
                'requirements_uz' => "- Tozalik standartlari\n- Transport imkoniyati afzal",
                'salary_min' => 2000000, 'salary_max' => 3500000, 'salary_type' => 'range',
                'work_type' => 'part_time', 'experience_required' => 'no_experience',
                'city' => 'Andijon', 'district' => null,
                'latitude' => 40.7821, 'longitude' => 72.3442,
                'contact_phone' => '+998742001020',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 23, 'applications_count' => 1,
            ],
            // cleaning-industrial
            [
                'employer' => 'Andijon Clean Service',
                'title_uz' => 'Sanoat tozalash xodimi',
                'title_ru' => 'Работник промышленной уборки',
                'category' => 'cleaning-industrial',
                'description_uz' => "Zavod va fabrika hududlarini tozalash. Maxsus jihozlar bilan.",
                'description_ru' => "Уборка территорий заводов и фабрик.",
                'requirements_uz' => "- Jismoniy sog'lom\n- Maxsus jihozlar bilan ishlash tayyor",
                'salary_min' => 2500000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Andijon', 'district' => null,
                'latitude' => 40.7821, 'longitude' => 72.3442,
                'contact_phone' => '+998742001020',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 19, 'applications_count' => 1,
            ],

            // ════════════════════════════════════════
            // OFIS VA ADMINISTRATOR (5 ta)
            // ════════════════════════════════════════

            // admin-reception
            [
                'employer' => 'Samarqand Grand Hotel',
                'title_uz' => 'Resepshnchi (mehmonxona)',
                'title_ru' => 'Ресепшионист (отель)',
                'category' => 'admin-reception',
                'description_uz' => "5 yulduzli mehmonxonaga resepshnchi. Ingliz va rus tili shart.",
                'description_ru' => "Ресепшионист в 5-звёздочный отель.",
                'requirements_uz' => "- Ingliz va rus tili\n- Yoqimli tashqi ko'rinish\n- Kompyuter bilimi",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Samarqand', 'district' => 'Registon',
                'latitude' => 39.6542, 'longitude' => 66.9597,
                'contact_phone' => '+998662331122',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 112, 'applications_count' => 8,
            ],
            // admin-secretary
            [
                'employer' => 'Namangan Building',
                'title_uz' => 'Kotiba (qurilish kompaniyasi)',
                'title_ru' => 'Секретарь (строительная компания)',
                'category' => 'admin-secretary',
                'description_uz' => "Direktor kotibasini ishga olamiz. Hujjatlar boshqarish.",
                'description_ru' => "Секретарь директора. Делопроизводство.",
                'requirements_uz' => "- Kompyuter bilimi (Word, Excel)\n- Tashkilotchilik\n- O'zbek va rus tili",
                'salary_min' => 2500000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Namangan', 'district' => null,
                'latitude' => 40.9983, 'longitude' => 71.6726,
                'contact_phone' => '+998692223344',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 56, 'applications_count' => 4,
            ],
            // admin-hr
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'HR mutaxassisi (IT kompaniya)',
                'title_ru' => 'HR специалист (IT компания)',
                'category' => 'admin-hr',
                'description_uz' => "IT sohasida xodimlarni qidirish va ishga olish. Employer branding.",
                'description_ru' => "Рекрутинг IT специалистов. Employer branding.",
                'requirements_uz' => "- HR tajribasi 1+ yil\n- IT sohasini tushunish\n- Ingliz tili afzal",
                'salary_min' => 5000000, 'salary_max' => 9000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 145, 'applications_count' => 11,
            ],
            // admin-manager
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Ofis menejeri',
                'title_ru' => 'Офис менеджер',
                'category' => 'admin-manager',
                'description_uz' => "Ofis ishlarini tashkil qilish. Ta'minot, jihozlar, uchrashuvlar.",
                'description_ru' => "Организация офисных работ.",
                'requirements_uz' => "- Tashkilotchilik qobiliyati\n- Kompyuter bilimi\n- Muloqotchanlik",
                'salary_min' => 3500000, 'salary_max' => 6000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => 'Chilonzor',
                'latitude' => 41.2630, 'longitude' => 69.2086,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 87, 'applications_count' => 6,
            ],
            // admin-callcenter
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Call-center operatori',
                'title_ru' => 'Оператор call-центра',
                'category' => 'admin-callcenter',
                'description_uz' => "Mijozlar qo'ng'iroqlariga javob berish. CRM tizimda ishlash.",
                'description_ru' => "Приём звонков клиентов. Работа в CRM.",
                'requirements_uz' => "- Yoqimli ovoz\n- Stressga chidamlilik\n- Kompyuter bilimi",
                'salary_min' => 2500000, 'salary_max' => 4000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => 41.3000, 'longitude' => 69.2700,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 156, 'applications_count' => 12,
            ],

            // ════════════════════════════════════════
            // ISHLAB CHIQARISH (4 ta)
            // ════════════════════════════════════════

            // production-operator
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Stanok operatori (to\'quv tsekhi)',
                'title_ru' => 'Оператор станка (ткацкий цех)',
                'category' => 'production-operator',
                'description_uz' => "To'quv stanoklarini boshqarish. Yaponiya ishlab chiqarish stanoklari.",
                'description_ru' => "Управление ткацкими станками.",
                'requirements_uz' => "- Texnik ma'lumot\n- Stanoklar tajribasi afzal\n- Ehtiyotkorlik",
                'salary_min' => 3000000, 'salary_max' => 5000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => 'Sanoat zonasi',
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 67, 'applications_count' => 5,
            ],
            // production-sewing
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Tikuvchi (ayollar kiyimi)',
                'title_ru' => 'Швея (женская одежда)',
                'category' => 'production-sewing',
                'description_uz' => "Yevropa eksporti uchun ayollar kiyimlari. Zamonaviy Yaponiya stanoklari.",
                'description_ru' => "Пошив женской одежды на экспорт в Европу.",
                'requirements_uz' => "- Tikuvchilik 1+ yil\n- Sanoat mashinalari\n- Tezkorlik",
                'salary_min' => 3500000, 'salary_max' => 7000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => 'Sanoat zonasi',
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 95, 'applications_count' => 12,
            ],
            // production-packer
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Qadoqchi (tayyor mahsulot)',
                'title_ru' => 'Упаковщик (готовая продукция)',
                'category' => 'production-packer',
                'description_uz' => "Tayyor mahsulotlarni tekshirish va qadoqlash.",
                'description_ru' => "Проверка и упаковка готовой продукции.",
                'requirements_uz' => "- Tajriba shart emas\n- Diqqatlilik\n- Jismoniy sog'lom",
                'salary_min' => 2000000, 'salary_max' => 3000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Farg\'ona', 'district' => 'Sanoat zonasi',
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 34, 'applications_count' => 3,
            ],
            // production-technologist
            [
                'employer' => 'Farg\'ona Tekstil',
                'title_uz' => 'Texnolog (to\'qimachilik)',
                'title_ru' => 'Технолог (текстильное производство)',
                'category' => 'production-technologist',
                'description_uz' => "Ishlab chiqarish texnologiyalarini nazorat qilish va optimallashtirish.",
                'description_ru' => "Контроль и оптимизация производственных технологий.",
                'requirements_uz' => "- Texnologiya ma'lumoti\n- Sifat nazorati\n- Tajriba 2+ yil",
                'salary_min' => 5000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => '1-3',
                'city' => 'Farg\'ona', 'district' => 'Sanoat zonasi',
                'latitude' => 40.3842, 'longitude' => 71.7889,
                'contact_phone' => '+998731234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 45, 'applications_count' => 3,
            ],

            // ════════════════════════════════════════
            // BOSHQA (3 ta)
            // ════════════════════════════════════════

            // other-freelance
            [
                'employer' => 'Digital Marketing Pro',
                'title_uz' => 'Freelance video montajchi',
                'title_ru' => 'Фриланс видеомонтажёр',
                'category' => 'other-freelance',
                'description_uz' => "Reklama videolari montaji. Premiere Pro yoki DaVinci Resolve.",
                'description_ru' => "Монтаж рекламных видеороликов.",
                'requirements_uz' => "- Video montaj tajribasi\n- Premiere Pro/DaVinci\n- Portfolio",
                'salary_min' => 3000000, 'salary_max' => 8000000, 'salary_type' => 'range',
                'work_type' => 'remote', 'experience_required' => '1-3',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998909876543',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 234, 'applications_count' => 18,
            ],
            // other-parttime
            [
                'employer' => 'Toshkent Express Delivery',
                'title_uz' => 'Yarim stavka operator (kechki)',
                'title_ru' => 'Оператор на полставки (вечерняя)',
                'category' => 'other-parttime',
                'description_uz' => "Kechki smena 18:00-22:00. Buyurtma qabul qilish va taqsimlash.",
                'description_ru' => "Вечерняя смена 18:00-22:00. Приём заказов.",
                'requirements_uz' => "- Smartfon/kompyuter\n- Muloqotchanlik\n- Talaba bo'lsa ham mumkin",
                'salary_min' => 1500000, 'salary_max' => 2500000, 'salary_type' => 'range',
                'work_type' => 'part_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => null,
                'latitude' => null, 'longitude' => null,
                'contact_phone' => '+998901001010',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 312, 'applications_count' => 25,
            ],
            // other-internship
            [
                'employer' => 'TechUz Solutions',
                'title_uz' => 'IT stajirovka (frontend)',
                'title_ru' => 'IT стажировка (frontend)',
                'category' => 'other-internship',
                'description_uz' => "3 oylik stajirovka dasturi. HTML, CSS, JavaScript, Vue.js o'rgatiladi.",
                'description_ru' => "3-месячная стажировка. HTML, CSS, JavaScript, Vue.js.",
                'requirements_uz' => "- Dasturlashga qiziqish\n- HTML/CSS asoslari\n- O'rganishga tayyor",
                'salary_min' => 1000000, 'salary_max' => 2000000, 'salary_type' => 'range',
                'work_type' => 'full_time', 'experience_required' => 'no_experience',
                'city' => 'Toshkent', 'district' => 'Yunusobod',
                'latitude' => 41.3111, 'longitude' => 69.2797,
                'contact_phone' => '+998901234567',
                'is_top' => false, 'is_urgent' => false,
                'views_count' => 567, 'applications_count' => 45,
            ],
        ];
    }

    private function createVacancies(array $employers): void
    {
        foreach ($this->getVacancyData() as $v) {
            $employerName = $v['employer'];
            unset($v['employer']);

            $defaults = [
                'employer_id' => $employers[$employerName]->id,
                'responsibilities_uz' => null,
                'responsibilities_ru' => null,
                'contact_method' => 'telegram',
                'status' => 'active',
                'published_at' => now()->subDays(rand(1, 14)),
                'expires_at' => now()->addDays(rand(7, 30)),
                'top_until' => $v['is_top'] ? now()->addDays(7) : null,
                'urgent_until' => $v['is_urgent'] ? now()->addDays(3) : null,
                'has_questionnaire' => false,
            ];

            Vacancy::create(array_merge($defaults, $v));
        }
    }
}
